export const COUNTRY_SUGGESTIONS = [
  "Nepal",
  "India",
  "China",
  "Bangladesh",
  "Sri Lanka",
  "Pakistan",
  "Myanmar",
  "Thailand",
  "Vietnam",
  "Indonesia",
  "Malaysia",
  "Singapore",
  "Japan",
  "South Korea",
  "United Arab Emirates",
  "Saudi Arabia",
  "United States",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Turkey",
  "Australia",
  "Canada",
  "Brazil",
];
